// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VideoGameAgeLimitQuestionnaire.WEB.Models;

namespace VideoGameAgeLimitQuestionnaire.WEB.Migrations
{
    [DbContext(typeof(QuestionnaireContext))]
    partial class QuestionnaireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("VideoGameAgeLimitQuestionnaire.WEB.Models.BinaryQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DeterminateAnswer");

                    b.Property<int>("Order");

                    b.Property<int?>("ResultId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("BinaryQuestions");
                });

            modelBuilder.Entity("VideoGameAgeLimitQuestionnaire.WEB.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("VideoGameAgeLimitQuestionnaire.WEB.Models.BinaryQuestion", b =>
                {
                    b.HasOne("VideoGameAgeLimitQuestionnaire.WEB.Models.Result", "Result")
                        .WithMany("BinaryQuestions")
                        .HasForeignKey("ResultId");
                });
#pragma warning restore 612, 618
        }
    }
}
